# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ac_input', [dirname(__file__)])
        except ImportError:
            import _ac_input
            return _ac_input
        if fp is not None:
            try:
                _mod = imp.load_module('_ac_input', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ac_input = swig_import_helper()
    del swig_import_helper
else:
    import _ac_input
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_ac_input.IRQ_AC_OUT_swigconstant(_ac_input)
IRQ_AC_OUT = _ac_input.IRQ_AC_OUT

_ac_input.IRQ_AC_COUNT_swigconstant(_ac_input)
IRQ_AC_COUNT = _ac_input.IRQ_AC_COUNT
class ac_input_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ac_input_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ac_input_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["irq"] = _ac_input.ac_input_t_irq_set
    __swig_getmethods__["irq"] = _ac_input.ac_input_t_irq_get
    if _newclass:
        irq = _swig_property(_ac_input.ac_input_t_irq_get, _ac_input.ac_input_t_irq_set)
    __swig_setmethods__["avr"] = _ac_input.ac_input_t_avr_set
    __swig_getmethods__["avr"] = _ac_input.ac_input_t_avr_get
    if _newclass:
        avr = _swig_property(_ac_input.ac_input_t_avr_get, _ac_input.ac_input_t_avr_set)
    __swig_setmethods__["value"] = _ac_input.ac_input_t_value_set
    __swig_getmethods__["value"] = _ac_input.ac_input_t_value_get
    if _newclass:
        value = _swig_property(_ac_input.ac_input_t_value_get, _ac_input.ac_input_t_value_set)

    def __init__(self):
        this = _ac_input.new_ac_input_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _ac_input.delete_ac_input_t
    __del__ = lambda self: None
ac_input_t_swigregister = _ac_input.ac_input_t_swigregister
ac_input_t_swigregister(ac_input_t)


def ac_input_init(avr, b):
    return _ac_input.ac_input_init(avr, b)
ac_input_init = _ac_input.ac_input_init
# This file is compatible with both classic and new-style classes.


