import distutils.sysconfig
import os

SWIG='.'
SIMAVR = SWIG+'/simavr'  # simavr path

SIM = SIMAVR + '/simavr/sim'
CORES = SIMAVR + '/simavr/cores'
INCLUDE_SIMAVR = SIMAVR + '/simavr'
INCLUDE_AVR = SWIG+'/include'
PARTS = SWIG+'/parts'

env = Environment(
#                  variables=vars,
                  ENV=os.environ,
                  CCFLAGS=[
                           '-Wall',
                           '--std=gnu99',
                           ],
                  CPPDEFINES=['NO_COLOR'],
                  );



#######################################
# swig simavr
########################################

swig_simavr = env.SharedLibrary(
                  'simavr',
                  source=[
                       'simavr.i',
                       Glob(SIM + '/*.c'),
                       Glob(CORES + '/sim_*.c'),
                       'simavr_logger.cpp',
                   ],
                        LIBS=['elf'],
                    SWIGFLAGS=['-python'],
                    SHLIBPREFIX="_",
                    CPPPATH=[
                                 SIM,
                                 INCLUDE_AVR,
                                 INCLUDE_SIMAVR,
                                 distutils.sysconfig.get_python_inc(),
                            ],
                    SWIGPATH=[
                                 SIM,
                                 ],
                  )

def part(name):
    cfile = Dir(PARTS).File(name + '.c')
    ifile = Dir(SWIG).File(name + '.i')

    swig_part = env.SharedLibrary(
                      name,
                      source=[
                                cfile,
                              ifile,
#                       'sim/sim_cycle_timers.c',
#                       'sim/sim_irq.c',
#                       'sim/sim_io.c',
#                       Glob('sim/*.c'),
#                       Glob('cores/sim_*.c'),
                       ],
#                        LIBS=['elf'],
                        SWIGFLAGS=['-python'],
                        SHLIBPREFIX="_",
                        CPPPATH=[
                                 SIM,
                                 INCLUDE_AVR,
                                 INCLUDE_SIMAVR,
                                 distutils.sysconfig.get_python_inc(),
                                 PARTS,
                                ],
                        SWIGPATH=[
                                 SIM,
                                 PARTS,
                                 ]
                      )


#######################################
# swig parts
########################################
part('sgm7')
part('ledrow')
part('inverter')
part('hd44780')
part('ac_input')
part('button')
part('uart_udp')
part('spk')
part('uart_buff')
